apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: default
spec:
  storageClassName: wp-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/wp-data/
